{{- if .Values.alloy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alloy-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{ toYaml .Values.alloy.env | indent 2 }}
{{- end }}
