apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-helper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: learn-helper
  template:
    metadata:
      labels:
        app: learn-helper
      annotations:
        checksum/learn-helper-env: {{ toYaml .Values.env.learnHelper | sha256sum | quote }}
        checksum/postgres-env: {{ toYaml .Values.env.postgres | sha256sum | quote }}
    spec:
      containers:
        - name: app
          image: learn-helper:local
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: learn-helper-env
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
