services:
  app:
    build: .
    ports:
      - "4321:4321"
    env_file:
      - .env
    environment:
      - ASTRO_DB_REMOTE_URL=file:./data.db
    volumes:
      - ./.astro/data.db:/app/data.db
    profiles:
      - production
