export enum EventType {
  UserVocabularyItemDiscovered = 'user-vocabulary-item-discovered',
  UserVocabularyItemDiscoveryUndone = 'user-vocabulary-item-discovery-undone',
  UserVocabularyItemTaskFailed = 'user-vocabulary-item-task-failed',
  UserVocabularyItemTaskShowcaseViewed = 'user-vocabulary-item-task-showcase-viewed',
  UserVocabularyItemTaskPassed = 'user-vocabulary-item-task-passed',
  UserVocabularyItemTaskRetryPassed = 'user-vocabulary-item-task-retry-passed',
  UserVocabularyItemTaskHintUsed = 'user-vocabulary-item-task-hint-used',
  UserVocabularyItemTaskGenerated = 'user-vocabulary-item-task-generated',
  UserVocabularyItemMovedToNextStep = 'user-vocabulary-item-moved-to-next-step',
  UserVocabularyItemProgressReset = 'user-vocabulary-item-progress-reset',
  UserVocabularyItemRemovedFromList = 'user-vocabulary-item-removed-from-list',
  VocabularyItemUpdated = 'vocabulary-item-updated',
  VocabularyItemGenerated = 'vocabulary-item-generated',
  ReadingUploaded = 'reading-uploaded',
  ReadingDeleted = 'reading-deleted',
  ReadingSelectionTranslationGenerated = 'reading-selection-translation-generated',
  ReadingTimeSpent = 'reading-time-spent',
}

export enum UserVocabularyItemTaskType {
  Showcase = 'showcase',
  VocabularyItemToDefinition = 'vocabulary-item-to-definition',
  DefinitionToVocabularyItem = 'definition-to-vocabulary-item',
  VocabularyItemToTranslation = 'vocabulary-item-to-translation',
  TranslationToVocabularyItem = 'translation-to-vocabulary-item',
  PronunciationToVocabularyItem = 'pronunciation-to-vocabulary-item',
  TranslateEnglishSentence = 'translate-english-sentence',
  TranslateUkrainianSentence = 'translate-ukrainian-sentence',
}
