{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{ toYaml .Values.cloudflared.env | indent 2 }}
{{- end }}
