apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - learn-helper-api.ingress-route.yml
  - learn-helper-favicon.ingress-route.yml
  - learn-helper-media.ingress-route.yml
  - learn-helper.ingress-route.yml
