apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learn-helper
resources:
  - postgres-data.persistent-volume-claim.yml
  - postgres.deployment.yml
  - postgres.service.yml
secretGenerator:
  - name: postgres-env
    envs:
      - .env
