/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/statistics': typeof StatisticsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/statistics': typeof StatisticsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/statistics': typeof StatisticsRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/error' | '/login' | '/statistics' | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error' | '/login' | '/statistics' | '/vocabulary'
  id: '__root__' | '/' | '/error' | '/login' | '/statistics' | '/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  StatisticsRoute: typeof StatisticsRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  StatisticsRoute: StatisticsRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
