/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthVocabularyRouteImport } from './routes/_auth/vocabulary'
import { Route as AuthStatisticsRouteImport } from './routes/_auth/statistics'
import { Route as AuthVocabularyUserVocabularyListIdRouteImport } from './routes/_auth/vocabulary_.$userVocabularyListId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVocabularyRoute = AuthVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatisticsRoute = AuthStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVocabularyUserVocabularyListIdRoute =
  AuthVocabularyUserVocabularyListIdRouteImport.update({
    id: '/vocabulary_/$userVocabularyListId',
    path: '/vocabulary/$userVocabularyListId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/statistics': typeof AuthStatisticsRoute
  '/vocabulary': typeof AuthVocabularyRoute
  '/api/$': typeof ApiSplatRoute
  '/vocabulary/$userVocabularyListId': typeof AuthVocabularyUserVocabularyListIdRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/statistics': typeof AuthStatisticsRoute
  '/vocabulary': typeof AuthVocabularyRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AuthIndexRoute
  '/vocabulary/$userVocabularyListId': typeof AuthVocabularyUserVocabularyListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_auth/statistics': typeof AuthStatisticsRoute
  '/_auth/vocabulary': typeof AuthVocabularyRoute
  '/api/$': typeof ApiSplatRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/vocabulary_/$userVocabularyListId': typeof AuthVocabularyUserVocabularyListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/statistics'
    | '/vocabulary'
    | '/api/$'
    | '/vocabulary/$userVocabularyListId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/statistics'
    | '/vocabulary'
    | '/api/$'
    | '/'
    | '/vocabulary/$userVocabularyListId'
  id:
    | '__root__'
    | '/_auth'
    | '/error'
    | '/login'
    | '/_auth/statistics'
    | '/_auth/vocabulary'
    | '/api/$'
    | '/_auth/'
    | '/_auth/vocabulary_/$userVocabularyListId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vocabulary': {
      id: '/_auth/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthVocabularyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/statistics': {
      id: '/_auth/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthStatisticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vocabulary_/$userVocabularyListId': {
      id: '/_auth/vocabulary_/$userVocabularyListId'
      path: '/vocabulary/$userVocabularyListId'
      fullPath: '/vocabulary/$userVocabularyListId'
      preLoaderRoute: typeof AuthVocabularyUserVocabularyListIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthStatisticsRoute: typeof AuthStatisticsRoute
  AuthVocabularyRoute: typeof AuthVocabularyRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthVocabularyUserVocabularyListIdRoute: typeof AuthVocabularyUserVocabularyListIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthStatisticsRoute: AuthStatisticsRoute,
  AuthVocabularyRoute: AuthVocabularyRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthVocabularyUserVocabularyListIdRoute:
    AuthVocabularyUserVocabularyListIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
