apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cache-favicon.middleware.yml
  - cache-html.middleware.yml
  - cache-media.middleware.yml
  - compress.middleware.yml
  - ratelimit.middleware.yml
  - sec.middleware.yml
