# Token bucket: 100 request burst, refills 50/s
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
  namespace: learn-helper
spec:
  rateLimit:
    average: 50
    burst: 100
